services:
  db:
    image: mariadb:10.11
    container_name: ngopss_db
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: gin_app

    ports:
      - "3307:3306"

    volumes:
      - ngopss_db_data:/var/lib/mysql

volumes:
  ngopss_db_data: